-- PostgreSQL schema for Fabflix.
-- In pgAdmin, create/select the "moviedb" database first, then run this file.

DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS creditcards;
DROP TABLE IF EXISTS genres_in_movies;
DROP TABLE IF EXISTS stars_in_movies;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS stars;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS employees;

CREATE TABLE movies (
    id VARCHAR(10) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    year INT NOT NULL,
    director VARCHAR(255) NOT NULL
);

CREATE TABLE stars (
    id VARCHAR(10) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    birthYear INT DEFAULT NULL
);

CREATE TABLE stars_in_movies (
    starId VARCHAR(10),
    movieId VARCHAR(10),
    PRIMARY KEY (starId, movieId),
    FOREIGN KEY (starId) REFERENCES stars(id),
    FOREIGN KEY (movieId) REFERENCES movies(id)
);

CREATE TABLE genres (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE genres_in_movies (
    genreId INT,
    movieId VARCHAR(10),
    PRIMARY KEY (genreId, movieId),
    FOREIGN KEY (genreId) REFERENCES genres(id),
    FOREIGN KEY (movieId) REFERENCES movies(id)
);

CREATE TABLE creditcards (
    id VARCHAR(20) PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    expiration DATE NOT NULL
);

CREATE TABLE customers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    ccId VARCHAR(20) NOT NULL,
    address VARCHAR(200) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    FOREIGN KEY (ccId) REFERENCES creditcards(id)
);

CREATE TABLE sales (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customerId INT NOT NULL,
    movieId VARCHAR(10) NOT NULL,
    saleDate DATE NOT NULL,
    FOREIGN KEY (customerId) REFERENCES customers(id),
    FOREIGN KEY (movieId) REFERENCES movies(id)
);

CREATE TABLE ratings (
    movieId VARCHAR(10) PRIMARY KEY,
    rating FLOAT NOT NULL,
    numVotes INT NOT NULL,
    FOREIGN KEY (movieId) REFERENCES movies(id)
);

CREATE TABLE carts (
    customerId INT NOT NULL,
    movieId VARCHAR(10) NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    PRIMARY KEY (customerId, movieId),
    FOREIGN KEY (customerId) REFERENCES customers(id),
    FOREIGN KEY (movieId) REFERENCES movies(id)
);

CREATE TABLE employees (
    email VARCHAR(100) PRIMARY KEY,
    password VARCHAR(128) NOT NULL,
    fullname VARCHAR(100) NOT NULL
);

CREATE INDEX idx_genres_name ON genres(name);
CREATE INDEX idx_stars_name ON stars(name);
CREATE INDEX idx_movies_title ON movies(title);
CREATE INDEX idx_movies_id ON movies(id);
CREATE INDEX idx_stars_in_movies_starId_movieId ON stars_in_movies(starId, movieId);
CREATE INDEX idx_genres_in_movies_genreId_movieId ON genres_in_movies(genreId, movieId);

INSERT INTO creditcards (id, firstName, lastName, expiration)
VALUES ('9999000011112222', 'Terry', 'Kim', '2030-12-31')
ON CONFLICT (id) DO NOTHING;

INSERT INTO customers (firstName, lastName, ccId, address, email, password)
VALUES ('Terry', 'Kim', '9999000011112222', '123 Test St', 'terry@test.com', 'password')
ON CONFLICT (email) DO NOTHING;

INSERT INTO employees (email, password, fullname)
VALUES ('admin@fabflix.com', 'admin', 'Fabflix Admin')
ON CONFLICT (email) DO NOTHING;
